baseURL: https://leonard-schmitz-website.netlify.app/
languageCode: en-us
title: Leonard's Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      This website has been created as part of my coding assignemnt for my master in financial analysis. Feel free to browse the different tiles and I hope you enjoy the content.
    title: HI, I'M LEONARD SCHMITZ WELCOME TO MY WEBSITE
    blog: {}
  contact:
    address:  
      - city: London NW1 4SA
        country: United Kingdom
        street: London Business School, Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: lschmitz.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+49) 15159073915 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    # copyright: Company Name
    enable: yes
    #quicklinks:
      #  text: 'Design: '
     # - alt: HTML5 UP
       # url: https://www.html5up.net
    social:
      #- icon: fa-twitter
       # label: Twitter
        #url: https://www.twitter.com/samnanda1
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/leonard.schmitz.9/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/leonard_schmitz
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/leonardschmitz98
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/leonard-schmitz-51266a13b/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
     # - name: Blogs
      #  url: blogs
      #- name: Generic Blog
        #url: blogs/ipsum
      #- name: Elements
       # url: elements.html
    menu: Menu
   # subtitle: By HTML5 Up
   # title: Forty
  tiles:
    enable: yes
    showcase:
      - image: projects/me
        #subtitle: Charity Mission
        title: About Me
        url: blogs/ipsum
      - image: projects/LBS
       # subtitle: Ipsum Dolor Sit Amet
        title: Education
        url: blogs/magna
      - image: projects/cv
       # subtitle: Feugiat Amet Tempus
        title: Internships
        url: blogs/tempus
      - image: projects/coding
       # subtitle: Feugiat Amet Tempus
        title: Coding Project
        url: blogs/aliquam
      - image: projects/USA
       # subtitle: Lorem Etiam Nullam
        title: Exchange Semesters
        url: blogs/exchange
      - image: projects/
       # subtitle: Nisl Sed Aliquam
        title: Sport
        url: blogs/sport
      
 # two:
  #  buttonText: Get Started
   # enable: yes
    #subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
    #  \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
     # condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      #pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
  #    Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
   #   amet pharetra et feugiat tempus."
    #title: Massa libero
    #url: blogs
